### PR TITLE
Klapligehesten patch 1

### PR DESCRIPTION
**Pull request by klapligehesten**

### CODE REVIEW

**Comment by klapligehesten** [comment]
Thank’s for the good work :)

Du you think it’s the effort worth to deaminize rtl-ais?

 

Fra: dgiardini [mailto:notifications@github.com] 
Sendt: 10. maj 2016 23:20
Til: dgiardini/rtl-ais <rtl-ais@noreply.github.com>
Kopi: Peter Schultz <hp@hpes.dk>; Author <author@noreply.github.com>
Emne: Re: [dgiardini/rtl-ais] Klapligehesten patch 1 (#4)

 

Merged #4 <https://github.com/dgiardini/rtl-ais/pull/4> .

**Comment by nunojpg** [comment]
I would say deamonize (as in run the the background) is a function of the init system that is now available in all major distributions, so there is no need for it.

**Comment by klapligehesten** [comment]
Point taken. I’ll forget about it. Maybe I’ll make some work on calibrate instead. 

I thought to fork kalibrate-rtl and implement a auto calibrating. 

 

Fra: Nuno Goncalves [mailto:notifications@github.com] 
Sendt: 11. maj 2016 12:23
Til: dgiardini/rtl-ais <rtl-ais@noreply.github.com>
Kopi: Peter Schultz <hp@hpes.dk>; Author <author@noreply.github.com>
Emne: Re: [dgiardini/rtl-ais] Klapligehesten patch 1 (#4)

 

I would say deamonize (as in run the the background) is a function of the init system that is now available in all major distributions, so there is no need for it.

**Comment by dgiardini** [comment]
Thanks for the contribs :-)
Would be nice to have a routine inside rtl-ais, as part of it; kalibrate-rtl routines would be great. Other approach I was seeing, is tuning a known FM station, and look at the DC component that is proportional to the error; but for now, I have no time to code and experiment,

**Pull request merged**
