### PR TITLE
Not a PR: thoughts on decoding libraries?

### PR DESCRIPTION
**Pull request by ianfixes**
Hi-

I maintain some ruby libraries that parse AIS sentences.  It looks like your library outputs AIS sentences.

* https://github.com/ianfixes/nmea_plus_google_earth (frontend) 
* https://github.com/ianfixes/nmea_plus (backend parser)
 
I was wondering whether there is any value in putting example code on my `nmea_plus` gem for how to link the output of `rtl-ais` to the input of my parser.  What do you think?

Also, what hardware would I need to even test this library out for myself?

### CODE REVIEW

**Comment by dgiardini** [comment]
Hi Ian

   If  you are interested in using rtl-ais along your program, you may need
first some info about software defined radio (SDR)  and the specific
hardware
we use for this, that is a DVB-T dongle. A good starting point here:
https://www.rtl-sdr.com/about-rtl-sdr
   You'll need also an antenna, and be located near (some miles)  the
passing vessels.
   You'll also need to do some procedure to get the tunning error for the
specfic dongle you have (aka ppm error), and pass that number as parameter
of rtl-ais. Look at the README file for
   some directions, or search for "rtl-sdr ppm" on google.
  Good luck !

**Comment by ianfixes** [comment]
Thanks.  Does `rtl-ais` have a debug mode of some sort where it will output a dummy sentence (like `$GPZDA`, the current local date and time) to help test anything consuming its output?

I will submit a real PR against the README with the data you provided here.

**Comment by dgiardini** [comment]
rtl-ais doesn't have such debug mode, and only outputs  AIVDM / AIVDO
sentences. If you are interested in that kind of sentences for
testing, you can download AISDecoder and
follow the instructions here:
https://github.com/freerange/ais-on-sdr/wiki/Testing-AISDecoder#with-an-audio-file



On Mon, Mar 2, 2020 at 10:38 AM Ian <notifications@github.com> wrote:
>
> Thanks. Does rtl-ais have a debug mode of some sort where it will output a dummy sentence (like $GPZDA, the current local date and time) to help test anything consuming its output?
>
> I will submit a real PR against the README with the data you provided here.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
----------------------------------------------------------------------------------------------
This message represents the official view of the voices in my head

**Comment by ianfixes** [comment]
I guess what I'm asking is how the various output options work.  Let's move this discussion to #21

**Pull request closed without merging**
